name = "Tranquilpeak"
license = "GNU General Public License v3.0"
licenselink = "https://github.com/indy/hugo-tranquilpeak-theme/blob/master/LICENSE"
description = "A responsive theme for Hugo based on Tranquilpeak"
homepage = "https://github.com/indy/hugo-tranquilpeak-theme"
tags = ["minimal", "responsive", "personal"]
features = ["minimal", "responsive"]
min_version = 0.20

[author]
  name = "Inderjit Gill"
  homepage = "https://github.com/indy"

[original]
  name = "Tranquilpeak"
  homepage = "https://github.com/kakawait"
  repo = "https://github.com/kakawait/hugo-tranquilpeak-theme.git"
